import { patternTemplate as T } from "../../core/pattern-template";
import { defineSubject } from "../../core/subjects";
import { defineInstitution } from "../../core/define-institution";

export const shinhan = /* @__PURE__ */ defineInstitution({
  id: "shinhan",
  code: "088",
  aliasCodes: ["021", "026", "028"],
  nameKo: "신한은행",
  nameEn: "Shinhan Bank",
  category: "bank",
  aliases: ["신한", "조흥은행"],
  priority: 95,
  successorOf: ["chohung", "shinhan-legacy"],
  patterns: [
    {
      template: T("XXX-XXX-XXXXXX"),
      kind: "new",
      identifierPosition: { start: 0, length: 3 },
      identifiers: [
        "100",
        "101",
        "102",
        "103",
        "104",
        "105",
        "106",
        "107",
        "108",
        "109",
        "160",
        "161",
        "110",
        "111",
        "112",
        "113",
        "114",
        "115",
        "116",
        "117",
        "118",
        "119",
        "120",
        "121",
        "122",
        "123",
        "124",
        "125",
        "126",
        "127",
        "128",
        "129",
        "130",
        "131",
        "132",
        "133",
        "134",
        "135",
        "136",
        "137",
        "138",
        "139",
        "140",
        "141",
        "142",
        "143",
        "144",
        "145",
        "146",
        "147",
        "148",
        "149",
        "150",
        "151",
        "152",
        "153",
        "154",
        "155",
        "156",
        "157",
        "158",
        "159",
        "268",
        "269",
        "298",
      ],
      subjectPosition: { start: 0, length: 3 },
      subjects: [
        ...["100", "101", "102", "103", "104", "105", "106", "107", "108", "109", "160", "161"].map(
          (code) => defineSubject({ code, category: "ordinary" }),
        ),
        ...[
          "110",
          "111",
          "112",
          "113",
          "114",
          "115",
          "116",
          "117",
          "118",
          "119",
          "120",
          "121",
          "122",
          "123",
          "124",
          "125",
          "126",
          "127",
          "128",
          "129",
          "130",
          "131",
          "132",
          "133",
          "134",
          "135",
          "136",
          "137",
          "138",
          "139",
        ].map((code) => defineSubject({ code, category: "savings" })),
        ...["140", "141", "142", "143", "144", "145", "146", "147", "148", "149"].map((code) =>
          defineSubject({ code, category: "corporate-free" }),
        ),
        ...["150", "151", "152", "153", "154"].map((code) =>
          defineSubject({ code, category: "current" }),
        ),
        ...["155", "156", "157", "158", "159"].map((code) =>
          defineSubject({ code, category: "household-current" }),
        ),
        defineSubject({
          code: "268",
          category: "isa",
          allowsWithdrawal: false,
        }),
        defineSubject({
          code: "269",
          category: "isa",
          allowsWithdrawal: false,
        }),
        defineSubject({
          code: "298",
          category: "installment",
          label: "청년희망펀드",
          allowsWithdrawal: false,
        }),
      ],
      effectiveFrom: "2006-10-09",
    },
    {
      template: T("XXX-XXX-XXXXXXX-X"),
      kind: "virtual",
      subjectPosition: { start: 0, length: 3 },
      subjects: [
        defineSubject({ code: "560", category: "ordinary", virtual: true }),
        defineSubject({ code: "561", category: "ordinary", virtual: true }),
        defineSubject({ code: "562", category: "ordinary", virtual: true }),
      ],
    },
    {
      template: T("XXX-XX-XXXXX-X"),
      kind: "merged-legacy",
      subjectPosition: { start: 3, length: 2 },
      subjects: [
        defineSubject({ code: "01", category: "ordinary" }),
        defineSubject({ code: "09", category: "ordinary" }),
        defineSubject({ code: "61", category: "ordinary" }),
        defineSubject({ code: "04", category: "savings" }),
        defineSubject({ code: "05", category: "savings" }),
        defineSubject({ code: "06", category: "free-savings" }),
        defineSubject({ code: "08", category: "free-savings" }),
        defineSubject({ code: "02", category: "household-current" }),
        defineSubject({ code: "07", category: "current" }),
        defineSubject({ code: "03", category: "corporate-free" }),
      ],
      note: "(구)조흥(021)",
    },
    {
      template: T("XXX-XX-XXXXXXX-X"),
      kind: "virtual",
      subjectPosition: { start: 3, length: 2 },
      subjects: [
        defineSubject({ code: "81", category: "ordinary", virtual: true }),
        defineSubject({ code: "82", category: "ordinary", virtual: true }),
      ],
      note: "(구)조흥(021) 가상계좌",
    },
    {
      template: T("XXX-XX-XXXXX-X"),
      kind: "merged-legacy",
      subjectPosition: { start: 3, length: 2 },
      subjects: [
        defineSubject({ code: "01", category: "ordinary" }),
        defineSubject({ code: "02", category: "savings" }),
        defineSubject({ code: "11", category: "savings" }),
        defineSubject({ code: "13", category: "savings" }),
        defineSubject({ code: "12", category: "free-savings" }),
        defineSubject({ code: "03", category: "household-current" }),
        defineSubject({ code: "04", category: "current" }),
        defineSubject({ code: "05", category: "corporate-free" }),
      ],
      note: "(구)신한(026)",
    },
    {
      template: T("XXX-XX-XXXXX-X"),
      kind: "virtual",
      subjectPosition: { start: 3, length: 2 },
      subjects: [defineSubject({ code: "99", category: "ordinary", virtual: true })],
      note: "(구)신한(026) 가상계좌",
    },
    {
      template: T("XXX-XXX-XXXXXXX-X"),
      kind: "virtual",
      subjectPosition: { start: 3, length: 3 },
      subjects: [defineSubject({ code: "901", category: "ordinary", virtual: true })],
      note: "(구)신한(026) 가상계좌 14d",
    },
  ],
});
